version: "3.9"
services:
  app:
    build:
      context: ./app
      dockerfile: dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    links:
      - db
    environment:
      DATABASE_URL: postgres://root:root@db:5432/zensho?sslmode=disable

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

  db:
    build: 
      context: ./db
      dockerfile: dockerfile.dev
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: zensho
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data:
    external: true