FROM golang:alpine

COPY . /app
WORKDIR /app

RUN apk add curl && \
    curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /bin && \
    chmod +x /bin/air

RUN go mod download

CMD [ "/bin/air", "-c", ".air.conf", "main.go" ]